openapi: "3.0.0"
info:
  version: 1.0.0
  title: Productos
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /:
    get:
      summary: List all products
      operationId: getProductos
      tags:
        - productos
      responses:
        '200':
          description: List all products
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Productos"
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Add new product
      operationId: postProductos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Producto"      
      tags:
        - productos
      responses:
        '201':
          description: Null response
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Producto:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
          pattern: "^C.*"
        precio:
          type: number
          format: double
        categoria:
          type: string 
    Productos:
      type: array
      items:
        $ref: "#/components/schemas/Producto"    
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string